#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_WALRUS                              107
#define IDI_SMALL                               108
#define IDD_WALRUS_DIALOG                       109
#define IDC_DEBUG                               1001
#define IDC_BUCKETS                             1002
#define IDC_RULE_SIZE                           1003
#define IDC_WALRUS                              40000
#define IDS_APP_TITLE                           40001
#define IDC_PICK                                40004
#define IDC_BUCKET_NEW                          40006
#define IDC_BUCKET_DELETE                       40008
#define IDC_BUCKET_NAME                         40010
#define IDC_IDENTITIES                          40012
#define IDC_IDENTITY_NEW                        40015
#define IDC_IDENTITY_DELETE                     40016
#define IDC_IDENTITY_TITLE                      40019
#define IDC_IDENTITY_CLASS                      40020
#define IDC_IDENTITY_STEAL                      40022
#define IDC_REGION_NEW                          40026
#define IDC_REGION_DELETE                       40027
#define IDC_REGIONS                             40028
#define IDC_REGION_NAME                         40030
#define IDC_REGION_ALL                          40032
#define IDC_REGION_WHICH                        40035
#define IDC_REGION_MONITOR                      40036
#define IDC_REGION_TOP                          40039
#define IDC_REGION_BOTTOM                       40041
#define IDC_REGION_LEFT                         40043
#define IDC_REGION_RIGHT                        40045
#define IDC_REGION_COORDS                       40046
#define IDC_RULES                               40050
#define IDC_RULE_NEW                            40051
#define IDC_RULE_DELETE                         40052
#define IDC_RULE_FROM                           40054
#define IDC_RULE_TO                             40056
#define IDC_RULE_MAXIMIZE                       40069
#define IDC_RULE_MINIMIZE                       40070
#define IDC_RULE_OVERLAP                        40071
#define IDC_RULE_SPLIT                          40072
#define IDC_RULE_HORIZONTAL                     40074
#define IDC_RULE_VERTICAL                       40076
#define IDC_RULE_PERCENT                        40078
#define IDC_RULE_SIDE                           40080
#define IDC_RULE_REST                           40081
#define IDC_REGION_STEAL                        40083
